#!/bin/bash

title=$(playerctl.py metadata title 2>/dev/null|| echo "")
artist=$(playerctl.py metadata artist 2>/dev/null || echo "")
playPauze=$(playerctl.py status 2>/dev/null || echo "")
playerName=$(cat ~/.playerctl-player)

fullText=""

if [ "$artist" ]
then
	fullText+="${artist}: "
fi

if [ "$title" ]
then
	fullText+="${title}"
fi

shortText=$fullText

if [ "$(echo $playerName | grep -vy "No players")" ]
then
  fullText+=" ($playerName)"
fi

if [ "$fullText" ]
then
	echo $fullText
  echo $shortText
else
	echo "No playerctl playing"
fi


case $BLOCK_BUTTON in
  # 1) playerctl play-pause ;;
  4) playerctl.py play ;; # scroll up, increase
  5) playerctl.py pause ;; # scroll down, decrease
esac
